var points = [
	{name: "VVD", countPoints: 0},
	{name: "CDA", countPoints: 0},
	{name: "PVV", countPoints: 0},
	{name: "D66", countPoints: 0},
	{name: "GroenLinks", countPoints: 0},
	{name: "SP", countPoints: 0},
	{name: "PvdA", countPoints: 0},
	{name: "ChristenUnie", countPoints:0},
	{name: "Partij voor de Dieren", countPoints: 0},
	{name: "SGP", countPoints: 0},
	{name: "DENK", countPoints: 0},
	{name: "Forum voor Democratie", countPoints: 0},
	{name: "OndernemersPartij", countPoints: 0},
	{name: "VNL", countPoints: 0},
	{name: "Nieuwe Wegen", countPoints: 0},
	{name: "De Burger Beweging", countPoints: 0},
	{name: "Piratenpartij", countPoints: 0},
	{name: "Artikel 1", countPoints: 0},
	{name: "Libertarische Partij", countPoints: 0},
];

var points2 = {
	VVD: 0,
	CDA: 0,
	PVV: 0,
	D66: 0,
	GroenLinks: 0,
	SP: 0,
	PvdA: 0,
	Partij_voor_de_Dieren: 0,
	SGP: 0,
	DENK: 0,
	Forum_voor_Democratie: 0,
	OndernemersPartij: 0,
	VNL: 0,
	Nieuwe_Wegen: 0,
	De_Burger_beweging: 0,
	Piratenpartij: 0,
	Artikel_1: 0,
	Libertarische_Partij: 0,
}
